// Finds code addresses referenced only indirectly (data pointers, lis/addi pairs)
// that rexglue's analysis did not register as functions, and emits [functions]
// TOML entries for them.
//
// Inputs: decrypted guest image (0x82000000-based), codegen.partition.json
// (known function starts), generated recomp sources (jump-table labels).
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;

public static class FindMissingFuncs
{
    const uint ImageBase = 0x82000000;
    static byte[] img;

    static uint W(uint addr) { long o = addr - ImageBase; return (uint)(img[o] << 24 | img[o + 1] << 16 | img[o + 2] << 8 | img[o + 3]); }

    static bool IsTerminator(uint w)
    {
        if (w == 0x4E800020 || w == 0x4E800420) return true;   // blr, bctr
        if ((w >> 26) == 18 && (w & 3) == 0) return true;       // b target
        return w == 0;                                          // padding
    }

    public static int Run(string imagePath, string partitionJson, string generatedDir,
                          uint textStart, uint textEnd, string outToml)
    {
        img = File.ReadAllBytes(imagePath);

        var known = new SortedSet<uint>();
        foreach (Match m in Regex.Matches(File.ReadAllText(partitionJson), "\"([0-9A-F]{8})\"\\s*:"))
            known.Add(Convert.ToUInt32(m.Groups[1].Value, 16));

        var labels = new HashSet<uint>();
        foreach (var f in Directory.GetFiles(generatedDir, "*_recomp.*.cpp"))
            foreach (Match m in Regex.Matches(File.ReadAllText(f), "^loc_([0-9A-F]{8}):", RegexOptions.Multiline))
                labels.Add(Convert.ToUInt32(m.Groups[1].Value, 16));

        // Import thunks (resolved by the runtime) occupy the tail of .text; skip them.
        uint thunkStart = textEnd;
        foreach (Match m in Regex.Matches(File.ReadAllText(Path.Combine(generatedDir, "..", "..", "codegen.log")),
                                          "FunctionNode 0x([0-9A-F]{8}) \\(__imp__"))
            thunkStart = Math.Min(thunkStart, Convert.ToUInt32(m.Groups[1].Value, 16));
        Func<uint, bool> inText = a => a >= textStart && a < thunkStart && (a & 3) == 0;
        var refs = new Dictionary<uint, string>();
        Action<uint, string> addRef = (t, why) => { if (!refs.ContainsKey(t)) refs[t] = why; };

        // 1. Pointers in non-text data
        for (uint a = ImageBase; a + 4 <= ImageBase + (uint)img.Length; a += 4)
        {
            if (a >= textStart && a < textEnd) continue;
            uint v = W(a);
            if (inText(v)) addRef(v, string.Format("data ptr @0x{0:X8}", a));
        }

        // 2. lis rX,hi ; addi/ori rY,rX,lo in text (track last lis per register)
        var lisVal = new uint?[32];
        for (uint a = textStart; a < textEnd; a += 4)
        {
            uint w = W(a);
            uint op = w >> 26;
            int rd = (int)((w >> 21) & 31), ra = (int)((w >> 16) & 31);
            if (op == 15 && ra == 0) { lisVal[rd] = (w & 0xFFFF) << 16; continue; }  // lis
            if ((op == 14 || op == 24) && lisVal[ra].HasValue)                       // addi / ori
            {
                uint lo = w & 0xFFFF;
                uint v = op == 14 ? lisVal[ra].Value + (uint)(short)lo : lisVal[ra].Value | lo;
                if (inText(v)) addRef(v, string.Format("lis/addi @0x{0:X8}", a));
            }
            if (IsTerminator(w)) Array.Clear(lisVal, 0, 32);
        }

        // Candidates: not known, not a jump-table label, preceded by a terminator.
        var cands = refs.Keys.Where(t => !known.Contains(t) && !labels.Contains(t) && IsTerminator(W(t - 4)) && W(t) != 0)
                             .OrderBy(t => t).ToList();
        var allStarts = new SortedSet<uint>(known); foreach (var c in cands) allStarts.Add(c);

        var sb = new StringBuilder();
        sb.AppendLine("# Auto-generated by tools/FindMissingFuncs.cs - functions only referenced indirectly.");
        sb.AppendLine("[functions]");
        foreach (var c in cands)
        {
            uint next = allStarts.GetViewBetween(c + 4, uint.MaxValue).DefaultIfEmpty(textEnd).First();
            // Run until the next known start or the first zero padding word.
            uint end = c;
            while (end < next && W(end) != 0) end += 4;
            sb.AppendFormat("0x{0:X8} = {{ end = 0x{1:X8} }}  # {2}\n", c, end, refs[c]);
        }
        File.WriteAllText(outToml, sb.ToString());
        Console.WriteLine("known={0} labels={1} code-refs={2} missing={3}", known.Count, labels.Count, refs.Count, cands.Count);
        return 0;
    }
}
